<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
	    $data = [
	        [1,"Afghanistan","AF","AFN","Afghani",1],
		    [2,"Albania","AL","ALL","Lek",1],
		    [3,"Algeria","DZ","DZD","Dinar",1],
		    [4,"American Samoa","AS","USD","Dollar",1],
		    [5,"Andorra","AD","EUR","Euro",1],
		    [6,"Angola","AO","AOA","Kwanza",1],
		    [7,"Anguilla","AI","XCD","Dollar",1],
		    [8,"Antigua and Barbuda","AG","XCD","Dollar",1],
		    [9,"Argentina","AR","ARS","Peso",1],
		    [10,"Armenia","AM","AMD","Dram",1],
		    [11,"Aruba","AW","AWG","Guilder",1],
		    [12,"Australia","AU","AUD","Dollar",1],
		    [13,"Austria","AT","EUR","Euro",1],
		    [14,"Azerbaijan","AZ","AZN","Manat",1],
		    [15,"Bahamas","BS","BSD","Dollar",1],
		    [16,"Bahrain","BH","BHD","Dinar",1],
		    [17,"Bangladesh","BD","BDT","Taka",1],
		    [18,"Barbados","BB","BBD","Dollar",1],
		    [19,"Belarus","BY","BYR","Ruble",1],
		    [20,"Belgium","BE","EUR","Euro",1],
		    [21,"Belize","BZ","BZD","Dollar",1],
		    [22,"Benin","BJ","XOF","Franc",1],
		    [23,"Bermuda","BM","BMD","Dollar",1],
		    [24,"Bhutan","BT","BTN","Ngultrum",1],
		    [25,"Bolivia","BO","BOB","Boliviano",1],
		    [26,"Bosnia and Herzegovina","BA","BAM","Marka",1],
		    [27,"Botswana","BW","BWP","Pula",1],
		    [28,"Bouvet Island","BV","NOK","Krone",1],
		    [29,"Brazil","BR","BRL","Real",1],
		    [30,"British Indian Ocean Territory","IO","USD","Dollar",1],
		    [31,"British Virgin Islands","VG","USD","Dollar",1],
		    [32,"Brunei","BN","BND","Dollar",1],
		    [33,"Bulgaria","BG","BGN","Lev",1],
		    [34,"Burkina Faso","BF","XOF","Franc",1],
		    [35,"Burundi","BI","BIF","Franc",1],
		    [36,"Cambodia","KH","KHR","Riels",1],
		    [37,"Cameroon","CM","XAF","Franc",1],
		    [38,"Canada","CA","CAD","Dollar",1],
		    [39,"Cape Verde","CV","CVE","Escudo",1],
		    [40,"Cayman Islands","KY","KYD","Dollar",1],
		    [41,"Central African Republic","CF","XAF","Franc",1],
		    [42,"Chad","TD","XAF","Franc",1],
		    [43,"Chile","CL","CLP","Peso",1],
		    [44,"China","CN","CNY","Yuan Renminbi",1],
		    [45,"Christmas Island","CX","AUD","Dollar",1],
		    [46,"Cocos Islands","CC","AUD","Dollar",1],
		    [47,"Colombia","CO","COP","Peso",1],
		    [48,"Comoros","KM","KMF","Franc",1],
		    [49,"Cook Islands","CK","NZD","Dollar",1],
		    [50,"Costa Rica","CR","CRC","Colon",1],
		    [51,"Croatia","HR","HRK","Kuna",1],
		    [52,"Cuba","CU","CUP","Peso",1],
		    [53,"Cyprus","CY","CYP","Pound",1],
		    [54,"Czech Republic","CZ","CZK","Koruna",1],
		    [55,"Democratic Republic of the Congo","CD","CDF","Franc",1],
		    [56,"Denmark","DK","DKK","Krone",1],
		    [57,"Djibouti","DJ","DJF","Franc",1],
		    [58,"Dominica","DM","XCD","Dollar",1],
		    [59,"Dominican Republic","DO","DOP","Peso",1],
		    [60,"East Timor","TL","USD","Dollar",1],
		    [61,"Ecuador","EC","USD","Dollar",1],
		    [62,"Egypt","EG","EGP","Pound",1],
		    [63,"El Salvador","SV","SVC","Colone",1],
		    [64,"Equatorial Guinea","GQ","XAF","Franc",1],
		    [65,"Eritrea","ER","ERN","Nakfa",1],
		    [66,"Estonia","EE","EEK","Kroon",1],
		    [67,"Ethiopia","ET","ETB","Birr",1],
		    [68,"Falkland Islands","FK","FKP","Pound",1],
		    [69,"Faroe Islands","FO","DKK","Krone",1],
		    [70,"Fiji","FJ","FJD","Dollar",1],
		    [71,"Finland","FI","EUR","Euro",1],
		    [72,"France","FR","EUR","Euro",1],
		    [73,"French Guiana","GF","EUR","Euro",1],
		    [74,"French Polynesia","PF","XPF","Franc",1],
		    [75,"French Southern Territories","TF","EUR","Euro  ",1],
		    [76,"Gabon","GA","XAF","Franc",1],
		    [77,"Gambia","GM","GMD","Dalasi",1],
		    [78,"Georgia","GE","GEL","Lari",1],
		    [79,"Germany","DE","EUR","Euro",1],
		    [80,"Ghana","GH","GHC","Cedi",1],
		    [81,"Gibraltar","GI","GIP","Pound",1],
		    [82,"Greece","GR","EUR","Euro",1],
		    [83,"Greenland","GL","DKK","Krone",1],
		    [84,"Grenada","GD","XCD","Dollar",1],
		    [85,"Guadeloupe","GP","EUR","Euro",1],
		    [86,"Guam","GU","USD","Dollar",1],
		    [87,"Guatemala","GT","GTQ","Quetzal",1],
		    [88,"Guinea","GN","GNF","Franc",1],
		    [89,"Guinea-Bissau","GW","XOF","Franc",1],
		    [90,"Guyana","GY","GYD","Dollar",1],
		    [91,"Haiti","HT","HTG","Gourde",1],
		    [92,"Heard Island and McDonald Islands","HM","AUD","Dollar",1],
		    [93,"Honduras","HN","HNL","Lempira",1],
		    [94,"Hong Kong","HK","HKD","Dollar",1],
		    [95,"Hungary","HU","HUF","Forint",1],
		    [96,"Iceland","IS","ISK","Krona",1],
		    [97,"India","IN","INR","Rupee",1],
		    [98,"Indonesia","ID","IDR","Rupiah",1],
		    [99,"Iran","IR","IRR","Rial",1],
		    [100,"Iraq","IQ","IQD","Dinar",1],
		    [101,"Ireland","IE","EUR","Euro",1],
		    [102,"Israel","IL","ILS","Shekel",1],
		    [103,"Italy","IT","EUR","Euro",1],
		    [104,"Ivory Coast","CI","XOF","Franc",1],
		    [105,"Jamaica","JM","JMD","Dollar",1],
		    [106,"Japan","JP","JPY","Yen",1],
		    [107,"Jordan","JO","JOD","Dinar",1],
		    [108,"Kazakhstan","KZ","KZT","Tenge",1],
		    [109,"Kenya","KE","KES","Shilling",1],
		    [110,"Kiribati","KI","AUD","Dollar",1],
		    [111,"Kuwait","KW","KWD","Dinar",1],
		    [112,"Kyrgyzstan","KG","KGS","Som",1],
		    [113,"Laos","LA","LAK","Kip",1],
		    [114,"Latvia","LV","LVL","Lat",1],
		    [115,"Lebanon","LB","LBP","Pound",1],
		    [116,"Lesotho","LS","LSL","Loti",1],
		    [117,"Liberia","LR","LRD","Dollar",1],
		    [118,"Libya","LY","LYD","Dinar",1],
		    [119,"Liechtenstein","LI","CHF","Franc",1],
		    [120,"Lithuania","LT","LTL","Litas",1],
		    [121,"Luxembourg","LU","EUR","Euro",1],
		    [122,"Macao","MO","MOP","Pataca",1],
		    [123,"Macedonia","MK","MKD","Denar",1],
		    [124,"Madagascar","MG","MGA","Ariary",1],
		    [125,"Malawi","MW","MWK","Kwacha",1],
		    [126,"Malaysia","MY","MYR","Ringgit",1],
		    [127,"Maldives","MV","MVR","Rufiyaa",1],
		    [128,"Mali","ML","XOF","Franc",1],
		    [129,"Malta","MT","MTL","Lira",1],
		    [130,"Marshall Islands","MH","USD","Dollar",1],
		    [131,"Martinique","MQ","EUR","Euro",1],
		    [132,"Mauritania","MR","MRO","Ouguiya",1],
		    [133,"Mauritius","MU","MUR","Rupee",1],
		    [134,"Mayotte","YT","EUR","Euro",1],
		    [135,"Mexico","MX","MXN","Peso",1],
		    [136,"Micronesia","FM","USD","Dollar",1],
		    [137,"Moldova","MD","MDL","Leu",1],
		    [138,"Monaco","MC","EUR","Euro",1],
		    [139,"Mongolia","MN","MNT","Tugrik",1],
		    [140,"Montserrat","MS","XCD","Dollar",1],
		    [141,"Morocco","MA","MAD","Dirham",1],
		    [142,"Mozambique","MZ","MZN","Meticail",1],
		    [143,"Myanmar","MM","MMK","Kyat",1],
		    [144,"Namibia","NA","NAD","Dollar",1],
		    [145,"Nauru","NR","AUD","Dollar",1],
		    [146,"Nepal","NP","NPR","Rupee",1],
		    [147,"Netherlands","NL","EUR","Euro",1],
		    [148,"Netherlands Antilles","AN","ANG","Guilder",1],
		    [149,"New Caledonia","NC","XPF","Franc",1],
		    [150,"New Zealand","NZ","NZD","Dollar",1],
		    [151,"Nicaragua","NI","NIO","Cordoba",1],
		    [152,"Niger","NE","XOF","Franc",1],
		    [153,"Nigeria","NG","NGN","Naira",1],
		    [154,"Niue","NU","NZD","Dollar",1],
		    [155,"Norfolk Island","NF","AUD","Dollar",1],
		    [156,"North Korea","KP","KPW","Won",1],
		    [157,"Northern Mariana Islands","MP","USD","Dollar",1],
		    [158,"Norway","NO","NOK","Krone",1],
		    [159,"Oman","OM","OMR","Rial",1],
		    [160,"Pakistan","PK","PKR","Rupee",1],
		    [161,"Palau","PW","USD","Dollar",1],
		    [162,"Palestinian Territory","PS","ILS","Shekel",1],
		    [163,"Panama","PA","PAB","Balboa",1],
		    [164,"Papua New Guinea","PG","PGK","Kina",1],
		    [165,"Paraguay","PY","PYG","Guarani",1],
		    [166,"Peru","PE","PEN","Sol",1],
		    [167,"Philippines","PH","PHP","Peso",1],
		    [168,"Pitcairn","PN","NZD","Dollar",1],
		    [169,"Poland","PL","PLN","Zloty",1],
		    [170,"Portugal","PT","EUR","Euro",1],
		    [171,"Puerto Rico","PR","USD","Dollar",1],
		    [172,"Qatar","QA","QAR","Rial",1],
		    [173,"Republic of the Congo","CG","XAF","Franc",1],
		    [174,"Reunion","RE","EUR","Euro",1],
		    [175,"Romania","RO","RON","Leu",1],
		    [176,"Russia","RU","RUB","Ruble",1],
		    [177,"Rwanda","RW","RWF","Franc",1],
		    [178,"Saint Helena","SH","SHP","Pound",1],
		    [179,"Saint Kitts and Nevis","KN","XCD","Dollar",1],
		    [180,"Saint Lucia","LC","XCD","Dollar",1],
		    [181,"Saint Pierre and Miquelon","PM","EUR","Euro",1],
		    [182,"Saint Vincent and the Grenadines","VC","XCD","Dollar",1],
		    [183,"Samoa","WS","WST","Tala",1],
		    [184,"San Marino","SM","EUR","Euro",1],
		    [185,"Sao Tome and Principe","ST","STD","Dobra",1],
		    [186,"Saudi Arabia","SA","SAR","Rial",1],
		    [187,"Senegal","SN","XOF","Franc",1],
		    [188,"Serbia and Montenegro","CS","RSD","Dinar",1],
		    [189,"Seychelles","SC","SCR","Rupee",1],
		    [190,"Sierra Leone","SL","SLL","Leone",1],
		    [191,"Singapore","SG","SGD","Dollar",1],
		    [192,"Slovakia","SK","SKK","Koruna",1],
		    [193,"Slovenia","SI","EUR","Euro",1],
		    [194,"Solomon Islands","SB","SBD","Dollar",1],
		    [195,"Somalia","SO","SOS","Shilling",1],
		    [196,"South Africa","ZA","ZAR","Rand",1],
		    [197,"South Georgia and the South Sandwich Islands","GS","GBP","Pound",1],
		    [198,"South Korea","KR","KRW","Won",1],
		    [199,"Spain","ES","EUR","Euro",1],
		    [200,"Sri Lanka","LK","LKR","Rupee",1],
		    [201,"Sudan","SD","SDD","Dinar",1],
		    [202,"Suriname","SR","SRD","Dollar",1],
		    [203,"Svalbard and Jan Mayen","SJ","NOK","Krone",1],
		    [204,"Swaziland","SZ","SZL","Lilangeni",1],
		    [205,"Sweden","SE","SEK","Krona",1],
		    [206,"Switzerland","CH","CHF","Franc",1],
		    [207,"Syria","SY","SYP","Pound",1],
		    [208,"Taiwan","TW","TWD","Dollar",1],
		    [209,"Tajikistan","TJ","TJS","Somoni",1],
		    [210,"Tanzania","TZ","TZS","Shilling",1],
		    [211,"Thailand","TH","THB","Baht",1],
		    [212,"Togo","TG","XOF","Franc",1],
		    [213,"Tokelau","TK","NZD","Dollar",1],
		    [214,"Tonga","TO","TOP","Pa'anga",1],
		    [215,"Trinidad and Tobago","TT","TTD","Dollar",1],
		    [216,"Tunisia","TN","TND","Dinar",1],
		    [217,"Turkey","TR","TRY","Lira",1],
		    [218,"Turkmenistan","TM","TMM","Manat",1],
		    [219,"Turks and Caicos Islands","TC","USD","Dollar",1],
		    [220,"Tuvalu","TV","AUD","Dollar",1],
		    [221,"U.S. Virgin Islands","VI","USD","Dollar",1],
		    [222,"Uganda","UG","UGX","Shilling",1],
		    [223,"Ukraine","UA","UAH","Hryvnia",1],
		    [224,"United Arab Emirates","AE","AED","Dirham",1],
		    [225,"United Kingdom","GB","GBP","Pound",1],
		    [226,"United States","US","USD","Dollar",1],
		    [227,"United States Minor Outlying Islands","UM","USD","Dollar ",1],
		    [228,"Uruguay","UY","UYU","Peso",1],
		    [229,"Uzbekistan","UZ","UZS","Som",1],
		    [230,"Vanuatu","VU","VUV","Vatu",1],
		    [231,"Vatican","VA","EUR","Euro",1],
		    [232,"Venezuela","VE","VEF","Bolivar",1],
		    [233,"Vietnam","VN","VND","Dong",1],
		    [234,"Wallis and Futuna","WF","XPF","Franc",1],
		    [235,"Western Sahara","EH","MAD","Dirham",1],
		    [236,"Yemen","YE","YER","Rial",1],
		    [237,"Zambia","ZM","ZMK","Kwacha",1],
		    [238,"Zimbabwe","ZW","ZWD","Dollar",1]
	    ];
	    foreach ($data as $i => $item ) {
	    	$data[ $i ] = [
	    		'id' => $item[0],
	    		'title' => $item[1],
	    		'code' => $item[2],
	    		'currency_name' => $item[3],
	    		'currency_code' => $item[4],
			    'currency_symbol' => '',
			    'active' => $item[5],
		    ];
	    }
	    DB::table( 'countries' )->truncate();
	    DB::table( 'countries' )->insert( $data );
    }
}
